CREATE TABLE IF NOT EXISTS encid_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  typ INTEGER NOT NULL,
  k BYTEA NOT NULL
);

CREATE INDEX IF NOT EXISTS encid_keys_typ_index ON encid_keys (typ);

CREATE TABLE IF NOT EXISTS encid_version (
  singleton INTEGER NOT NULL PRIMARY KEY,
  version INTEGER NOT NULL,
  CHECK (singleton = 0)
);

INSERT INTO encid_version (singleton, version) VALUES (0, 1)
ON CONFLICT (singleton) DO NOTHING;
