-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  typ INTEGER NOT NULL,
  k BYTEA NOT NULL
);

CREATE INDEX IF NOT EXISTS keys_typ_index ON keys (typ);

CREATE TABLE IF NOT EXISTS version (
  singleton INTEGER NOT NULL PRIMARY KEY,
  version INTEGER NOT NULL,
  CHECK (singleton = 0)
);

INSERT INTO version (singleton, version) VALUES (0, 1)
ON CONFLICT (singleton) DO NOTHING;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS version;
DROP TABLE IF EXISTS keys;
-- +goose StatementEnd
